version: '3.1'
services:
  api:
    build: .
    container_name: ecercice
    environment: 
      MONGO_URI: mongodb://mongodb:27017
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb
    image: devopsexercice

  mongodb:
    container_name: mongodb
    image: mongo:3.2.11
    ports:
      - "27017:27017"

  mongo_seed:
    container_name: mongo_dataset
    image: mongo:3.2.11
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ./mongo_dataset:/mongo_dataset
    command: sh /mongo_dataset/import.sh

